org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = minihud
mod_name = MiniHUD
author = masa
mod_file_name = minihud-fabric

# Current mod version
mod_version = 0.34.999-dev

# Required malilib version
malilib_version = 7ea385d3c5

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 25w04a
minecraft_version = 25w04a
mappings_version = 25w04a+build.10

fabric_loader_version = 0.16.10
mod_menu_version = 13.0.1
# fabric_api_version = 0.115.1+1.21.5
